/* Generated By:JJTree: Do not edit this line. ASTForInStatement.java */

package com.rohanclan.cfml.parser.cfscript;

public class ASTForInStatement extends SimpleNode {
  public ASTForInStatement(int id) {
    super(id);
  }

  public ASTForInStatement(SPLParser p, int id) {
    super(p, id);
  }

}
