/* Generated By:JJTree: Do not edit this line. ASTFunctionDeclNode.java */

package com.rohanclan.cfml.parser.cfscript;

public class ASTFunctionDeclNode extends SimpleNode {
	String name;
  public ASTFunctionDeclNode(int id) {
    super(id);
  }

  

}
