/* Generated By:JJTree: Do not edit this line. ASTFunctionDeclaration.java */

package org.cfeclipse.cfml.parser.cfscript;

public class ASTFunctionDeclaration extends SimpleNode {
	String name;
  public ASTFunctionDeclaration(int id) {
    super(id);
  }

  public ASTFunctionDeclaration(SPLParser p, int id) {
    super(p, id);
  }

}
