/* Generated By:JJTree: Do not edit this line. ASTStringLiteral.java */

package org.cfeclipse.cfml.parser.cfscript;

public class ASTStringLiteral extends SimpleNode {
	public String val;
  public ASTStringLiteral(int id) {
    super(id);
  }

  public ASTStringLiteral(SPLParser p, int id) {
    super(p, id);
  }

}
