/* Generated By:JJTree: Do not edit this line. ASTReturnStatement.java */

package org.cfeclipse.cfml.parser.cfscript;

public class ASTReturnStatement extends SimpleNode {
  public ASTReturnStatement(int id) {
    super(id);
  }

  public ASTReturnStatement(SPLParser p, int id) {
    super(p, id);
  }

}
