/* Generated By:JJTree: Do not edit this line. ASTFunctionCallNode.java */

package com.rohanclan.cfml.parser.cfscript;

public class ASTFunctionCallNode extends SimpleNode {
	String name;
	
	public ASTFunctionCallNode(int id) {
		super(id);
	}

	public String toString(String prefix) {
		return super.toString(prefix) + " func name is: " + name;
	}
}
