/* Generated By:JJTree: Do not edit this line. ASTIntLiteral.java */

package com.rohanclan.cfml.parser.cfscript;

public class ASTIntLiteral extends SimpleNode {
	public String val;
  public ASTIntLiteral(int id) {
    super(id);
  }

  public ASTIntLiteral(SPLParser p, int id) {
    super(p, id);
  }

}
