/* Generated By:JJTree: Do not edit this line. ASTSwitchLabel.java */

package com.rohanclan.cfml.parser.cfscript;

public class ASTSwitchLabel extends SimpleNode {
  public ASTSwitchLabel(int id) {
    super(id);
  }

  public ASTSwitchLabel(SPLParser p, int id) {
    super(p, id);
  }

}
