/* Generated By:JJTree: Do not edit this line. ASTTryStatement.java */

package com.rohanclan.cfml.parser.cfscript;

public class ASTTryStatement extends SimpleNode {
  public ASTTryStatement(int id) {
    super(id);
  }

  public ASTTryStatement(SPLParser p, int id) {
    super(p, id);
  }

}
