/* Generated By:JJTree: Do not edit this line. ASTSwitchStatement.java */

package org.cfeclipse.cfml.parser.cfscript;

public class ASTSwitchStatement extends SimpleNode {
  public ASTSwitchStatement(int id) {
    super(id);
  }

  public ASTSwitchStatement(SPLParser p, int id) {
    super(p, id);
  }

}
