/* Generated By:JJTree: Do not edit this line. ASTStrEQNode.java */

package org.cfeclipse.cfml.parser.cfscript;

public class ASTStrEQNode extends SimpleNode {
  public ASTStrEQNode(int id) {
    super(id);
  }

  public ASTStrEQNode(SPLParser p, int id) {
    super(p, id);
  }

}
