/* Generated By:JJTree: Do not edit this line. ASTForStatementNode.java */

package org.cfeclipse.cfml.parser.cfscript;

public class ASTForStatementNode extends SimpleNode {
  public ASTForStatementNode(int id) {
    super(id);
  }

  public String toString(String prefix) {
  	return super.toString(prefix) + " I am the for.";
  }
}
