/* Generated By:JJTree: Do not edit this line. ASTStrNEQNode.java */

package org.cfeclipse.cfml.parser.cfscript;

public class ASTStrNEQNode extends SimpleNode {
  public ASTStrNEQNode(int id) {
    super(id);
  }

  public ASTStrNEQNode(SPLParser p, int id) {
    super(p, id);
  }

}
