/* Generated By:JJTree: Do not edit this line. ASTFloatingPointLiteral.java */

package com.rohanclan.cfml.parser.cfscript;

public class ASTFloatingPointLiteral extends SimpleNode {
    public String val;
    public ASTFloatingPointLiteral(int id) {
        super(id);
    }

    public ASTFloatingPointLiteral(SPLParser p, int id) {
        super(p, id);
    }

}
