/* Generated By:JJTree&JavaCC: Do not edit this line. SPLParserConstants.java */
package com.rohanclan.cfml.parser.cfscript;

public interface SPLParserConstants {

  int EOF = 0;
  int FUNCTION = 8;
  int FOR = 9;
  int WHILE = 10;
  int DO = 11;
  int VAR = 12;
  int RETURN = 13;
  int CONTINUE = 14;
  int BREAK = 15;
  int SWITCH = 16;
  int CASE = 17;
  int _DEFAULT = 18;
  int TRY = 19;
  int CATCH = 20;
  int OR = 21;
  int AND = 22;
  int EQ = 23;
  int NEQ = 24;
  int GT = 25;
  int GTE = 26;
  int GE = 27;
  int LT = 28;
  int LTE = 29;
  int LE = 30;
  int INTEGER_LITERAL = 31;
  int STRING_LITERAL = 32;
  int FLOATING_POINT_LITERAL = 33;
  int IDENTIFIER = 58;
  int LETTER = 59;
  int DIGIT = 60;
  int ISNOT = 61;
  int SEMICOLON = 62;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"function\"",
    "\"for\"",
    "\"while\"",
    "\"do\"",
    "\"var\"",
    "\"return\"",
    "\"continue\"",
    "\"break\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"try\"",
    "\"catch\"",
    "\"or\"",
    "\"and\"",
    "\"eq\"",
    "\"neq\"",
    "\"gt\"",
    "\"gte\"",
    "\"ge\"",
    "\"lt\"",
    "\"lte\"",
    "\"le\"",
    "<INTEGER_LITERAL>",
    "<STRING_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"is\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"%\"",
    "\"/\"",
    "\".\"",
    "\"[\"",
    "\"]\"",
    "\"true\"",
    "\"false\"",
    "\",\"",
    "\"in\"",
    "\"{\"",
    "\"}\"",
    "\"if\"",
    "\"else\"",
    "\":\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"is not\"",
    "\";\"",
  };

}
