/* Generated By:JJTree: Do not edit this line. SPLParserTreeConstants.java */

package com.rohanclan.cfml.parser.cfscript;

public interface SPLParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTFUNCTIONDECLARATION = 1;
  public int JJTVARDECLARATION = 2;
  public int JJTVOID = 3;
  public int JJTASSIGNMENT = 4;
  public int JJTORNODE = 5;
  public int JJTANDNODE = 6;
  public int JJTBITWISEORNODE = 7;
  public int JJTBITWISEXORNODE = 8;
  public int JJTBITWISEANDNODE = 9;
  public int JJTNENODE = 10;
  public int JJTEQNODE = 11;
  public int JJTLTNODE = 12;
  public int JJTGTNODE = 13;
  public int JJTLENODE = 14;
  public int JJTGENODE = 15;
  public int JJTADDNODE = 16;
  public int JJTSUBTRACTNODE = 17;
  public int JJTMULNODE = 18;
  public int JJTDIVNODE = 19;
  public int JJTMODNODE = 20;
  public int JJTSTRUCTREFNODE = 21;
  public int JJTCFCMETHODCALLNODE = 22;
  public int JJTID = 23;
  public int JJTINTCONSTNODE = 24;
  public int JJTTRUENODE = 25;
  public int JJTFALSENODE = 26;
  public int JJTFORSTATEMENTNODE = 27;
  public int JJTFUNCTIONCALLNODE = 28;
  public int JJTPARAMETERLIST = 29;
  public int JJTBLOCK = 30;
  public int JJTSTATEMENTEXPRESSION = 31;
  public int JJTIFSTATEMENT = 32;
  public int JJTWHILESTATEMENT = 33;
  public int JJTDOSTATEMENT = 34;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "FunctionDeclaration",
    "VarDeclaration",
    "void",
    "Assignment",
    "OrNode",
    "AndNode",
    "BitwiseOrNode",
    "BitwiseXorNode",
    "BitwiseAndNode",
    "NENode",
    "EQNode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "AddNode",
    "SubtractNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "StructRefNode",
    "CFCMethodCallNode",
    "Id",
    "IntConstNode",
    "TrueNode",
    "FalseNode",
    "ForStatementNode",
    "FunctionCallNode",
    "ParameterList",
    "Block",
    "StatementExpression",
    "IfStatement",
    "WhileStatement",
    "DoStatement",
  };
}
