/* Generated By:JJTree&JavaCC: Do not edit this line. SPLParserConstants.java */
package com.rohanclan.cfml.parser.cfscript;

public interface SPLParserConstants {

  int EOF = 0;
  int FUNCTION = 8;
  int FOR = 9;
  int WHILE = 10;
  int DO = 11;
  int VAR = 12;
  int RETURN = 13;
  int EQ = 14;
  int NEQ = 15;
  int INT = 16;
  int BOOL = 17;
  int INTEGER_LITERAL = 18;
  int STRING_LITERAL = 19;
  int IDENTIFIER = 50;
  int LETTER = 51;
  int DIGIT = 52;
  int ISNOT = 53;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"function\"",
    "\"for\"",
    "\"while\"",
    "\"do\"",
    "\"var\"",
    "\"return\"",
    "\"eq\"",
    "\"neq\"",
    "\"int\"",
    "\"boolean\"",
    "<INTEGER_LITERAL>",
    "<STRING_LITERAL>",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"or\"",
    "\"and\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"is\"",
    "\"lt\"",
    "\"gt\"",
    "\"lte\"",
    "\"gte\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\".\"",
    "\"[\"",
    "\"]\"",
    "\"true\"",
    "\"false\"",
    "\";\"",
    "\",\"",
    "\"in\"",
    "\"{\"",
    "\"}\"",
    "\"if\"",
    "\"else\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"is not\"",
  };

}
