/* Generated By:JJTree&JavaCC: Do not edit this line. SPLParserConstants.java */
package com.rohanclan.cfml.parser.cfscript;

public interface SPLParserConstants {

  int EOF = 0;
  int FUNCTION = 6;
  int FOR = 7;
  int WHILE = 8;
  int DO = 9;
  int INT = 10;
  int BOOL = 11;
  int INTEGER_LITERAL = 12;
  int STRING_LITERAL = 13;
  int IDENTIFIER = 43;
  int LETTER = 44;
  int DIGIT = 45;
  int ISNOT = 46;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"function\"",
    "\"for\"",
    "\"while\"",
    "\"do\"",
    "\"int\"",
    "\"boolean\"",
    "<INTEGER_LITERAL>",
    "<STRING_LITERAL>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"or\"",
    "\"and\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"is\"",
    "\"lt\"",
    "\"gt\"",
    "\"lte\"",
    "\"gte\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\".\"",
    "\"[\"",
    "\"]\"",
    "\"true\"",
    "\"false\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"if\"",
    "\"else\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"is not\"",
  };

}
