/* Generated By:JJTree: Do not edit this line. ASTDoStatement.java */

package com.rohanclan.cfml.parser.cfscript;

public class ASTDoStatement extends SimpleNode {
  public ASTDoStatement(int id) {
    super(id);
  }

}
