/* Generated By:JJTree: Do not edit this line. ASTParameterList.java */

package org.cfeclipse.cfml.parser.cfscript;

public class ASTParameterList extends SimpleNode {
  public ASTParameterList(int id) {
    super(id);
  }

}
